[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "avx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "comtypes>=1.4.16",
    "docx>=0.2.4",
    "docx2pdf>=0.1.8",
    "flet[all]>=0.85.0",
    "markdown>=3.10.2",
    "markdownify>=1.2.2",
    "moviepy>=1.0.3",
    "pillow>=12.2.0",
    "ppt2pdf>=0.0.3",
    "pypandoc>=1.17",
    "rich>=15.0.0",
    "typer>=0.24.1",
]


[project.scripts]
avx = "avx.cli:main"
avx-ui = "ui.main:main"

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.0.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.14",
]
